name: Post

on:
  schedule:
    - cron: '20 11 * * 4'
  push:
    branches:
      - main

jobs:
  post:
    name: Post
    runs-on: ubuntu-latest
    env:
      REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID}}
      REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET}
      REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
      REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: mkdir -p .venv && pip install --upgrade pip && pip install pipenv && pipenv install --dev

      - name: Run script
        run: pipenv run python main.py
