name: Post

on:
  schedule:
    - cron: '10 11 * * 4'

jobs:
  post:
    name: Post
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: mkdir .venv -p && && pip install --upgrade pip && pip install pipenv && pipenv install --dev

      - name: Run script
        run: pipenv run python main.py
